### ISSUE TITLE
Time zone not recognized by joda-time

### ISSUE THREAD

**Issue by arminha** [arminha/worldclockwidget#60]
joda-time does not recognize 'Arctic/Longyearbyen' as a time zone ID

```
java.lang.IllegalArgumentException: The datetime zone id 'Arctic/Longyearbyen' is not recognised
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:229)
	at ch.corten.aha.worldclock.AddClockActivity$TimeZoneListFragment$1.bindView(AddClockActivity.java:99)
	at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:256)
```

**Comment by arminha** [comment]
According to joda-time Arctic/Longyearbyen is the same zone as Europe/Oslo
