### ISSUE TITLE
AddClockActivity is broken for Android 2.3

### ISSUE THREAD

**Issue by arminha** [arminha/worldclockwidget#61]
It dies with a NullPointerException

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.corten.aha.worldclock/ch.corten.aha.worldclock.AddClockActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1816)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1837)
	at android.app.ActivityThread.access$1500(ActivityThread.java:132)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1033)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:143)
	at android.app.ActivityThread.main(ActivityThread.java:4196)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at ch.corten.aha.worldclock.AddClockActivity$TimeZoneListFragment.onCreateOptionsMenu(AddClockActivity.java:153)
	at android.support.v4.app.Watson.onCreatePanelMenu(Watson.java:55)
	at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:560)
	at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:466)
	at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:265)
	at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:149)
	at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:155)
	at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:803)
	at ch.corten.aha.worldclock.AddClockActivity$TimeZoneListFragment.onActivityCreated(AddClockActivity.java:89)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1508)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:958)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:570)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1225)
	at android.app.Activity.performStart(Activity.java:3868)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1789)
	... 11 more
```

**Comment by sm4rk0** [comment]
I'm not an Android developer, but maybe one of these could help:
http://stackoverflow.com/questions/14286768/getactionview-of-my-menuitem-return-null
http://stackoverflow.com/questions/26219658/menuitem-getactionview-null-in-api-15
